networks:
  esdl_val_net:

services:
  esdl_validator:
#    build: .
    image: esdlmapeditoressim/esdlvalidator:0.0.8
    ports:
      - "3011:5000"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - validator-storage:/storage
    networks:
      - esdl_val_net
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-storage:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - esdl_val_net

volumes:
  validator-storage:
  mongo-storage: