version: '3'

networks:
  esdl_val_net:

services:
  esdlValidator:
    image: ci.tno.nl/warmingup/chess-preprocessor:latest
    ports:
      - "3011:5000"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - validator-storage:/storage
    networks:
      - esdl_val_net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-storage:/data/db
    networks:
      - esdl_val_net

volumes:
  validator-storage:
  mongo-storage: